### ISSUE TITLE
Type inference is passed ontology in incorrect format

### ISSUE THREAD

**Issue by kliegr** [KIZI/LinkedHypernymsDataset#4]
Type inference is passed an owl file (e.g. dbpedia_3.9.owl specified as dataset.ontology.path in module.properties), while the readAllITaxonomy method only supports .nt format. The readAllITaxonomy method incorrectly parses the file instead of raising an exception. This causes the type inference pruning algorithm not to remove the supertypes. As a result, the STI fails, assigning the most generic type.

To fix this error, it is either necessary to convert the .owl ontology to .nt format using e.g. http://www.l3s.de/~minack/rdf2rdf/, or rewrite the readAllITaxonomy method to support the owl format.

**Comment by propi** [comment]
Fixed! Now DBpedia ontology .owl (RDF/XML) is automatically converted to N-Triples within STI processing.
